name: "Build Alfred Postgres"

on:
  push:
    branches:
      - master
    paths:
      - docker/Dockerfile
      - docker/docker-entrypoint-initdb.d/*
  workflow_dispatch: # on button click

jobs:
  test:
    strategy:
      matrix:
        node-version: [22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker
        run: echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build PG Age Base
        run: docker build -t ghcr.io/herebedragonssystems/alfred-pg-age:16 -t gghcr.io/herebedragonssystems/alfred-pg-age:latest -f ./docker/Dockerfile .
      - name: Publish PG Age Base
        run: docker push ghcr.io/herebedragonssystems/alfred-pg-age:16 && docker push ghcr.io/herebedragonssystems/alfred-pg-age:latest
