name: "Build Alfred Postgres"

on:
  push:
    branches:
      - master
    paths:
      - docker/databases/Postgres.Dockerfile
      - docker/databases/docker-entrypoint-initdb.d/*
  workflow_dispatch: # on button click

jobs:
  test:
    strategy:
      matrix:
        node-version: [22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to docker
        run: echo ${{ secrets.CI_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
      - name: Build Couchdb Booter
        run: docker build -t ghcr.io/herebedragonssystems/alfred-pg:$(cat package.json | jq -r '.version') -t gghcr.io/herebedragonssystems/alfred-pg:latest -f ./docker/databases/Postgres.Dockerfile ./docker/databases
      - name: Publish Couchdb Booter
        run: docker push ghcr.io/herebedragonssystems/alfred-pg:$(cat package.json | jq -r '.version') && docker push ghcr.io/herebedragonssystems/alfred-pg:latest